language: python
python:
  - "3.5"
install:
  pip install -r requirements.txt;
script:
  - source extrator/test/test_env
  - flake8 .
  - nosetests
notifications:
  email:
    - felipe.gomes.ferreira@gmail.com